services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: FinanCia
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
  backend:
    build: ./
    container_name: financia-backend
    depends_on:
      - postgres
    ports:
      - "3420:3420"
volumes:
  postgres_data: